apiVersion: v1
kind: Pod

metadata:
  name: mydb-pod
  namespace: myspace
  labels:
    name: mydb-pod

spec:
  containers:
  - name: mydb-container
    image: stackupiss/northwind-db:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
  - name: myapp-container
    image: stackupiss/northwind-app:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
    env:
    - name : DB_HOST
      value: localhost