image:
  repository: munir07/day4app
  tag: v2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

version: v1

deployment:
  containerPort: 3000

param:
  appkey: 3af4185f06b6f8d839b72273c3d006f4
  defaultCity: Singapore

replicaCount: 1
productionEnv: false
productionReplicaCount: 2
