apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "weatherapp.fullname" . }}
  namespace: default
spec:
  hosts:
  - {{ .Values.gatewayhostname }}
  http:
  - route:
    - destination:
        host: {{ include "weatherapp.fullname" . }}